# Generated by Django 5.1.6 on 2025-02-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(default='flowers/default.jpg', upload_to='flowers/'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
